version: '3.8'

services:
  carnetizacion-digital-api-prod:
    container_name: carnetizacion-digital-api-prod
    build:
      context: ../..
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "5103:8080"
    networks:
      - network_prod
    labels:
      - com.carnetizacion.environment=prod
    command: >
      sh -c "
        echo 'Ejecutando migraciones de Entity Framework...';
        dotnet ef database update --project ./Entity/Entity.csproj --startup-project ./Web/Web.csproj;
        echo 'Migraciones completadas. Iniciando la API...';
        dotnet ./Web/bin/Release/net8.0/Web.dll
      "
networks:
  network_prod:
    external: true
