version: '3.8'

services:
  carnetizacion-digital-api-prod:
    container_name: carnetizacion-digital-api-prod
    build:
      context: ../..
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "5103:8080"
    networks:
      - network_prod
    depends_on:
      - carnetizacion-postgres-prod
    labels:
      - com.carnetizacion.environment=prod

networks:
  network_prod:
    external: true
